### ISSUE TITLE
Support parsing Moshi Json annotated data class constructor parameters

### ISSUE THREAD

**Issue by donfreiday** [tabilzad/ktor-docs-plugin#16]
```kotlin
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class SomeRequest(
    @Json(name = "some_id") // this should be reflected in the OpenAPI schema
    val someId: String = ""
```

should produce

```yaml
    my.package.SomeRequest:
      type: "object"
      properties:
        some_id:
          type: "string"
```

but presently results in

```yaml
    my.package.SomeRequest:
      type: "object"
      properties:
        someId:
          type: "string"
```
